
CREATE TABLE TEST_MEMBER(
    MID NVARCHAR2(10),
    MPW NVARCHAR2(10),
    MNAME NVARCHAR2(10),
    MBIRTH DATE
);

SELECT * FROM TEST_MEMBER;
SELECT * FROM TEST_MEMBER WHERE MID = 'lsw4656' and MPW = '1111'; 